### ISSUE TITLE
Error in parseWhatWhere

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#9]
```
Waar is Obama geboren?
<?xml version="1.0" encoding="UTF-8"?>
<alpino_ds version="1.5">
  <node begin="0" cat="top" end="5" id="0" rel="top">
    <node begin="0" cat="whq" end="4" id="1" rel="--">
      <node begin="0" end="1" frame="er_wh_loc_adverb" getal="getal" id="2" index="1" lcat="advp" lemma="waar" naamval="obl" pdtype="adv-pron" persoon="3o" pos="adv" postag="VNW(vb,adv-pron,obl,vol,3o,getal)" pt="vnw" rel="whd" root="waar" sense="waar" special="er_loc" status="vol" vwtype="vb" wh="ywh" word="Waar"/>
      <node begin="0" cat="sv1" end="4" id="3" rel="body">
        <node begin="1" end="2" frame="verb(unacc,sg_heeft,passive)" id="4" infl="sg_heeft" lcat="sv1" lemma="zijn" pos="verb" postag="WW(pv,tgw,ev)" pt="ww" pvagr="ev" pvtijd="tgw" rel="hd" root="ben" sc="passive" sense="ben" stype="whquestion" tense="present" word="is" wvorm="pv"/>
        <node begin="2" end="3" frame="proper_name(sg,'PER')" genus="zijd" getal="ev" graad="basis" id="5" index="2" lcat="np" lemma="Obama" naamval="stan" neclass="PER" ntype="eigen" num="sg" pos="name" postag="N(eigen,ev,basis,zijd,stan)" pt="n" rel="su" rnum="sg" root="Obama" sense="Obama" word="Obama"/>
        <node begin="0" cat="ppart" end="4" id="6" rel="vc">
          <node begin="0" end="1" id="7" index="1" rel="mod"/>
          <node begin="2" end="3" id="8" index="2" rel="obj1"/>
          <node begin="3" buiging="zonder" end="4" frame="verb(hebben,psp,transitive)" id="9" infl="psp" lcat="ppart" lemma="geboren" pos="verb" positie="vrij" postag="WW(vd,vrij,zonder)" pt="ww" rel="hd" root="geboren" sc="transitive" sense="geboren" word="geboren" wvorm="vd"/>
        </node>
      </node>
    </node>
    <node begin="4" end="5" frame="punct(vraag)" id="10" lcat="punct" lemma="?" pos="punct" postag="LET()" pt="let" rel="--" root="?" sense="?" special="vraag" word="?"/>
  </node>
  <sentence sentid="86.92.18.45">Waar is Obama geboren ?</sentence>
</alpino_ds>

Expected type: location
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    solutionList = preParseSentence(line)
  File "/Users/DanielHaitink/Documents/LanguagePractical/prePostParser.py", line 91, in preParseSentence
    solution = parseWhereWhen(alpinoXML, expectedAnswer)
  File "/Users/DanielHaitink/Documents/LanguagePractical/questionParser.py", line 431, in parseWhereWhen
    concepts.append(t.xpath('//node[@rel="obj1" and ../../@rel="su" and ../../../@rel="body"]', smart_strings=False)[0]);
IndexError: list index out of range
```

**Comment by Anco88** [comment]
check toegevoegd die controleerd of t.xpath('//node[@rel="obj1" and ../../@rel="su" and ../../../@rel="body"]', smart_strings=False)[0]);
wel bestaat
